import Hero from "@/components/helper/hero";
import Navbar from "@/components/navbar";
import { Inter } from "next/font/google";


export default function Home() {
  return (
      <div className="relative px-2 pb-2">
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
          <h1>zsfdsaf</h1>
        </div>
  );
}
