import Hero from "@/components/helper/hero";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className="relative pt-20 px-2 pb-2">

      <div>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
        <h1>safdsa</h1>
      </div>
    </div>
  );
}
